apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor-${IMAGE_TAG}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
        version: ${IMAGE_TAG}
        env: canary
    spec:
      containers:
        - name: event-processor
          image: groupassignmentregistry.azurecr.io/ecm3440/event-processor:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            #cpu and memory limit
            limits:
              memory: "550Mi"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: event-processor
spec:
  type: ClusterIP
  selector:
    app: event-processor
  ports:
    - port: 80
      targetPort: 8080

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: event-processor
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  rules:
    - host: event-processor.1ebc354abe5745168776.ukwest.aksapp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: event-processor
                port:
                  number: 80
