# name: Push

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

